#!/bin/bash
#
# host [ connect | disconnect ] <mac> <ip> <port> <switch>"
#
# TODO:
#   * add tunID
#   * remove sudo

MACADDR=$2
IPADDR=$3
PORT=$4
SWITCH=$5
VXLANID=100

# FIXME
VTEP_PORT=$(sudo ovs-ofctl show $SWITCH | grep vtep | cut -d'(' -f1)
VTEP_PORT=10

case $1 in
    connect)
        OP="add-flow"
        FLOW_SPLIT=""
        ;;

    disconnect)
        OP="del-flows"
        FLOW_SPLIT="-F ,actions"
        ;;

    *)
        echo "Usage: host [ connect | disconnect ] <mac> <ip> <port> <switch>"
        exit 1
esac

## declare ovswitch flows for each host
declare -a flows=( \
    # ingress local L2 switching
    "priority=10,table=0,dl_dst=$MACADDR,actions=output:$PORT" \
    "priority=10,table=0,arp,nw_dst=$IPADDR,actions=output:$PORT" \

    # ingress remote L2 switching
    "priority=10,table=0,tun_id=$VXLANID,dl_dst=$MACADDR,actions=output:$PORT" \
    "priority=10,table=0,tun_id=$VXLANID,arp,nw_dst=$IPADDR,actions=output:$PORT" \

    # egress remote L2 switching
    "priority=10,table=0,in_port=$PORT,actions=set_field:$VXLANID->tun_id,output:$VTEP_PORT" \

    # TODO - do I need default drop?
    #"table=0,priority=100,actions=drop"
)

## install flows
for i in "${flows[@]}"
do
    FLOW_STR=$(echo $i | awk $FLOW_SPLIT '{print $1}')

    #echo sudo ovs-ofctl $OP $SWITCH $FLOW_STR
    sudo ovs-ofctl $OP $SWITCH $FLOW_STR
done
